export const SELECT_VALUE = "SELECT_VALUE";
export const SELECT_TARGET_VALUE = "SELECT_TARGET_VALUE";
export const ADD_TARGET = "ADD_TARGET";
export const REMOVE_TARGET = "REMOVE_TARGET";
export const EDIT_TARGET = "EDIT_TARGET";
export const SET_JAMMING = "SET_JAMMING";
export const SET_ID_EDIT_TARGET = "SET_ID_EDIT_TARGET";
