name: CI/CD for React App

on:
  push:
    branches:
      - main  # Виконується при пуші в main
  pull_request:
    branches:
      - develop  # Виконується при створенні або оновленні Pull Request у гілку develop

jobs:
  build-and-deploy:
    # Цей job виконується тільки для пушів у main
    if: github.event_name == 'push' && contains(github.ref, 'refs/heads/main')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: List build directory
        run: ls -R ./build  # Перевіряємо, чи є директорія build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Вказуємо правильний шлях до директорії build

  pr-check:
    # Цей job виконується тільки для Pull Request у гілку develop
    if: github.event_name == 'pull_request' && github.base_ref == 'develop'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint  # Виконуємо перевірку стилю коду
